#Include class HookInstallFastM_LL.ahk
#Include ..\..\Classes\class WaitUntil.ahk
#Include class UserHookCallbackTo.ahk
#Include class HookConfig.ahk
#Include class HookInstall.ahk
#Include class HookSet.ahk
#Include class HookID.ahk
#Include class HookCallbackTo.ahk
#Include class HookUn.ahk
#Include class HookCallNext.ahk
#Include class HookHandle.ahk
#Include class UserHookCallbackTo.ahk
#Include class HookMensages.ahk
#Include ..\..\Classes\Constants Mensages.ahk